import type { ConditionalPrimitive, ProceduralShape } from "../engine/proceduralShape";
import type { AssetLibrary, Project } from "../types/schema";
import { buildHumanCharacterShape, HUMAN_CHARACTER_ACTIONS, HUMAN_CHARACTER_EXPRESSIONS } from "./characterShapes";

// Detailed 2.5D human character shapes are generated by buildHumanCharacterShape
// in ./characterShapes.ts — ~120 primitives per character covering hair locks,
// facial features (nose, lip, jaw, ears), clothing wrinkles, shoes with
// laces, and 5 action branches (idle / walking / attack / defend / victory).
const humanCharacterShape: ProceduralShape = buildHumanCharacterShape({
  hairStyle: "fringe",
  costume: "jacket",
  eyeStyle: "almond",
});
const childCharacterShape: ProceduralShape = buildHumanCharacterShape({
  scale: 0.82,
  hairStyle: "short",
  costume: "shirt",
  eyeStyle: "almond",
});
// Warrior — spiky hair + headband. Demonstrates the new hat/eyeStyle params.
const warriorCharacterShape: ProceduralShape = buildHumanCharacterShape({
  hairStyle: "spiky",
  hat: "headband",
  hatColor: "#c14a3a",
  costume: "tank",
  eyeStyle: "narrow",
  facialMarks: [{ kind: "scar_x", at: "left_cheek", color: "rgba(160,70,40,0.8)" }],
});
// Explorer — straw hat + open green vest + shorts. Original character built to
// showcase the new hat/shorts/marks pipeline (not a likeness of any
// existing fictional character).
const explorerCharacterShape: ProceduralShape = buildHumanCharacterShape({
  hairStyle: "short",
  hat: "straw",
  hatColor: "#dcc080",
  hatBandColor: "#3a6e4a",
  costume: "vest",
  shorts: true,
  eyeStyle: "almond",
  facialMarks: [{ kind: "scar_diagonal", at: "under_left_eye", color: "rgba(180,80,50,0.7)" }],
  chestEmblem: { color: "#f3ead0" },
});


const flashEffectShape: ProceduralShape = {
  preview: { fit: "center" },
  primitives: [
    // soft inner glow halo
    {
      kind: "circle",
      cx: 0,
      cy: 0,
      r: "60 + progress * 90",
      fill: {
        gradient: "radial",
        x0: 0,
        y0: 0,
        r0: 0,
        x1: 0,
        y1: 0,
        r1: "60 + progress * 90",
        stops: [
          { at: 0, color: "rgba(255, 246, 196, ${0.7 * (1 - progress)})" },
          { at: 0.55, color: "rgba(255, 213, 88, ${0.45 * (1 - progress)})" },
          { at: 1, color: "rgba(255, 196, 90, 0)" },
        ],
      },
    },
    // spiked star burst
    {
      kind: "starBurst",
      cx: 0,
      cy: 0,
      spikes: 12,
      outer: "90 + progress * 80",
      inner: 34,
      rotation: "progress * PI",
      fill: "rgba(255, 213, 88, ${1 - progress})",
      stroke: "rgba(198, 75, 58, ${1 - progress})",
      lineWidth: 8,
    },
  ],
};

const schoolbagShape: ProceduralShape = {
  preview: { fit: "center" },
  primitives: [
    // contact shadow under the bag
    { kind: "ellipse", cx: 0, cy: 12, rx: 60, ry: 14, fill: "rgba(20, 18, 16, 0.28)" },
    // body with linear lighting
    { kind: "roundedRect", x: -55, y: -78, w: 110, h: 76, r: 16, fill: "#385d82" },
    {
      kind: "roundedRect",
      x: -55,
      y: -78,
      w: 110,
      h: 76,
      r: 16,
      fill: {
        gradient: "linear",
        x0: -55,
        y0: -78,
        x1: 55,
        y1: -2,
        stops: [
          { at: 0, color: "rgba(255,255,255,0.28)" },
          { at: 0.5, color: "rgba(255,255,255,0)" },
          { at: 1, color: "rgba(0,0,0,0.28)" },
        ],
      },
    },
    // strap
    { kind: "arc", cx: 0, cy: -78, r: 38, startAngle: Math.PI, endAngle: Math.PI * 2, stroke: "#243d58", lineWidth: 9 },
    // pocket
    { kind: "roundedRect", x: -28, y: -58, w: 56, h: 26, r: 8, fill: "#f4b457" },
    { kind: "roundedRect", x: -28, y: -58, w: 56, h: 26, r: 8, fill: { gradient: "linear", x0: -28, y0: -58, x1: 28, y1: -32, stops: [{ at: 0, color: "rgba(255,255,255,0.35)" }, { at: 1, color: "rgba(0,0,0,0.18)" }] } },
    // upper-left specular highlight
    { kind: "ellipse", cx: -22, cy: -60, rx: 14, ry: 6, fill: "rgba(255,255,255,0.35)" },
  ],
};

// 2.5D living room — multi-layer with parallax.
// background: wall gradient, distant atmospheric haze, window with sky view
// midground: window frame, sofa volume, coffee table, floor perspective
// foreground: front-side of the coffee table + carpet edge that occludes
// characters when the camera pans.
const livingRoomShape: ProceduralShape = {
  preview: { fit: "contain" },
  // Aggressive parallax contrast so even a small camera pan is unmistakable:
  // background drifts at 0.25× camera speed, foreground races at 1.55×.
  parallax: { background: 0.25, midground: 1, foreground: 1.55 },
  primitives: [],
  layers: {
    background: [
      // Sky / wall split with atmospheric haze that cools toward the horizon.
      {
        kind: "rect",
        x: -400,
        y: 0,
        w: 2080,
        h: 720,
        fill: {
          gradient: "linear",
          x0: 0,
          y0: 0,
          x1: 0,
          y1: 720,
          stops: [
            { at: 0, color: "#dde8e7" },
            { at: 0.35, color: "#c8dad6" },
            { at: 0.58, color: "#a8c0bb" },
            { at: 0.59, color: "#88664e" },
            { at: 1, color: "#5b3f31" },
          ],
        },
      },
      // distant cool-blue haze band high on the wall — pushes the room back
      {
        kind: "rect",
        x: -400,
        y: 0,
        w: 2080,
        h: 240,
        fill: {
          gradient: "linear",
          x0: 0,
          y0: 0,
          x1: 0,
          y1: 240,
          stops: [
            { at: 0, color: "rgba(180, 198, 210, 0.55)" },
            { at: 1, color: "rgba(180, 198, 210, 0)" },
          ],
        },
      },
      // distant mountain silhouette far behind the back wall — only ever
      // peeks through the window, but its slow parallax makes the whole
      // back-of-room read as deep space.
      {
        kind: "polygon",
        points: [
          { x: 60, y: 350 },
          { x: 230, y: 200 },
          { x: 320, y: 250 },
          { x: 410, y: 180 },
          { x: 530, y: 270 },
          { x: 530, y: 460 },
          { x: 60, y: 460 },
        ],
        fill: {
          gradient: "linear",
          x0: 0,
          y0: 180,
          x1: 0,
          y1: 460,
          stops: [
            { at: 0, color: "#8aa6ad" },
            { at: 1, color: "#6e8a93" },
          ],
        },
      },
      // outdoor sky inside window opening
      {
        kind: "rect",
        x: 105,
        y: 105,
        w: 198,
        h: 320,
        fill: {
          gradient: "linear",
          x0: 0,
          y0: 105,
          x1: 0,
          y1: 425,
          stops: [
            { at: 0, color: "#c6dbe7" },
            { at: 1, color: "#88a7b4" },
          ],
        },
      },
      // distant cloud streak inside the window — slow parallax sells the
      // "outside is far away" cue.
      {
        kind: "ellipse",
        cx: 240,
        cy: 170,
        rx: 90,
        ry: 16,
        fill: "rgba(255,255,255,0.7)",
      },
      {
        kind: "ellipse",
        cx: 140,
        cy: 210,
        rx: 60,
        ry: 10,
        fill: "rgba(255,255,255,0.55)",
      },
      // soft sun glow seeping through the upper-left pane
      {
        kind: "circle",
        cx: 150,
        cy: 150,
        r: 110,
        fill: {
          gradient: "radial",
          x0: 150,
          y0: 150,
          r0: 0,
          x1: 150,
          y1: 150,
          r1: 110,
          stops: [
            { at: 0, color: "rgba(255, 244, 200, 0.7)" },
            { at: 1, color: "rgba(255, 244, 200, 0)" },
          ],
        },
      },
      // a framed picture on the back wall
      { kind: "rect", x: 470, y: 150, w: 110, h: 90, fill: "#caa872", shadow: { blur: 8, offsetY: 3, color: "rgba(0,0,0,0.25)" } },
      { kind: "rect", x: 482, y: 162, w: 86, h: 66, fill: "#7c95a3" },
      { kind: "line", x1: 525, y1: 130, x2: 525, y2: 150, stroke: "rgba(20,16,14,0.6)", lineWidth: 2 },
      // a second framed picture closer to right — gives parallax something
      // distinctive to push against on a left/right camera pan.
      { kind: "rect", x: 1080, y: 165, w: 95, h: 75, fill: "#8a6644", shadow: { blur: 8, offsetY: 3, color: "rgba(0,0,0,0.25)" } },
      { kind: "rect", x: 1090, y: 175, w: 75, h: 55, fill: "#c89878" },
    ],
    midground: [
      // window frame
      { kind: "rect", x: 84, y: 80, w: 245, h: 385, fill: "#e8f3ef", shadow: { blur: 18, offsetY: 6, color: "rgba(0,0,0,0.18)" } },
      // window panes (translucent so we can see the sky beneath)
      { kind: "rect", x: 105, y: 105, w: 88, h: 135, fill: "rgba(190, 220, 220, 0.35)" },
      { kind: "rect", x: 215, y: 105, w: 88, h: 135, fill: "rgba(190, 220, 220, 0.35)" },
      { kind: "rect", x: 105, y: 263, w: 88, h: 165, fill: "rgba(190, 220, 220, 0.35)" },
      { kind: "rect", x: 215, y: 263, w: 88, h: 165, fill: "rgba(190, 220, 220, 0.35)" },
      // diagonal specular sheen across the upper-left pane
      {
        kind: "polygon",
        points: [
          { x: 110, y: 105 },
          { x: 192, y: 105 },
          { x: 152, y: 240 },
          { x: 110, y: 240 },
        ],
        fill: {
          gradient: "linear",
          x0: 110,
          y0: 105,
          x1: 192,
          y1: 240,
          stops: [
            { at: 0, color: "rgba(255,255,255,0.5)" },
            { at: 1, color: "rgba(255,255,255,0)" },
          ],
        },
      },
      // sofa backrest with linear shading
      {
        kind: "rect",
        x: 760,
        y: 365,
        w: 300,
        h: 140,
        fill: "#6d4d3f",
        shadow: { blur: 18, offsetY: 8, color: "rgba(20,12,8,0.32)" },
      },
      {
        kind: "rect",
        x: 760,
        y: 365,
        w: 300,
        h: 140,
        fill: {
          gradient: "linear",
          x0: 760,
          y0: 365,
          x1: 1060,
          y1: 505,
          stops: [
            { at: 0, color: "rgba(255,255,255,0.18)" },
            { at: 0.6, color: "rgba(255,255,255,0)" },
            { at: 1, color: "rgba(0,0,0,0.32)" },
          ],
        },
      },
      // sofa base with radial volume
      { kind: "roundedRect", x: 720, y: 445, w: 400, h: 115, r: 24, fill: "#80614f" },
      {
        kind: "roundedRect",
        x: 720,
        y: 445,
        w: 400,
        h: 115,
        r: 24,
        fill: {
          gradient: "radial",
          x0: 870,
          y0: 470,
          r0: 0,
          x1: 920,
          y1: 502,
          r1: 220,
          stops: [
            { at: 0, color: "rgba(255,235,205,0.32)" },
            { at: 1, color: "rgba(20,12,8,0.32)" },
          ],
        },
      },
      // teal cushion with rim light
      { kind: "roundedRect", x: 770, y: 393, w: 300, h: 80, r: 28, fill: "#3d6269" },
      {
        kind: "roundedRect",
        x: 770,
        y: 393,
        w: 300,
        h: 80,
        r: 28,
        fill: {
          gradient: "linear",
          x0: 770,
          y0: 393,
          x1: 1070,
          y1: 473,
          stops: [
            { at: 0, color: "rgba(255,255,255,0.22)" },
            { at: 1, color: "rgba(0,0,0,0.22)" },
          ],
        },
      },
      // coffee table top
      {
        kind: "roundedRect",
        x: 510,
        y: 574,
        w: 240,
        h: 42,
        r: 14,
        fill: "#b98e55",
        shadow: { blur: 14, offsetY: 6, color: "rgba(20,12,8,0.28)" },
      },
      {
        kind: "roundedRect",
        x: 510,
        y: 574,
        w: 240,
        h: 42,
        r: 14,
        fill: {
          gradient: "linear",
          x0: 510,
          y0: 574,
          x1: 750,
          y1: 616,
          stops: [
            { at: 0, color: "rgba(255,235,200,0.32)" },
            { at: 1, color: "rgba(0,0,0,0.24)" },
          ],
        },
      },
      // floor perspective lines (faint, behind characters)
      { kind: "line", x1: 0, y1: 545, x2: 1280, y2: 545, stroke: "rgba(45, 52, 51, 0.16)", lineWidth: 3 },
      { kind: "line", x1: 640, y1: 545, x2: 330, y2: 720, stroke: "rgba(45, 52, 51, 0.16)", lineWidth: 3 },
      { kind: "line", x1: 640, y1: 545, x2: 950, y2: 720, stroke: "rgba(45, 52, 51, 0.16)", lineWidth: 3 },
    ],
    foreground: [
      // Front edge of the coffee table — occludes character legs when the
      // camera dollies in close to the table.
      { kind: "rect", x: 535, y: 610, w: 18, h: 58, fill: "#6e4a35" },
      { kind: "rect", x: 705, y: 610, w: 18, h: 58, fill: "#6e4a35" },
      // a soft front-edge carpet shadow band
      {
        kind: "rect",
        x: -200,
        y: 684,
        w: 1680,
        h: 36,
        fill: {
          gradient: "linear",
          x0: 0,
          y0: 684,
          x1: 0,
          y1: 720,
          stops: [
            { at: 0, color: "rgba(30, 42, 42, 0.28)" },
            { at: 1, color: "rgba(30, 42, 42, 0)" },
          ],
        },
      },
      // Tall floor lamp on the lower-LEFT foreground — sits in front of the
      // window/wall and visibly slides hard during a camera pan because
      // foreground parallax = 1.55.
      { kind: "rect", x: 36, y: 360, w: 12, h: 320, fill: "#2c2218" },
      { kind: "polygon", points: [
        { x: -18, y: 360 },
        { x: 102, y: 360 },
        { x: 78, y: 300 },
        { x: 6, y: 300 },
      ], fill: "#d8b56b", shadow: { blur: 14, color: "rgba(0,0,0,0.35)" } },
      { kind: "polygon", points: [
        { x: -18, y: 360 },
        { x: 102, y: 360 },
        { x: 78, y: 300 },
        { x: 6, y: 300 },
      ], fill: { gradient: "linear", x0: 0, y0: 300, x1: 0, y1: 360, stops: [{ at: 0, color: "rgba(255,240,200,0.5)" }, { at: 1, color: "rgba(0,0,0,0.3)" }] } },
      { kind: "ellipse", cx: 42, cy: 685, rx: 56, ry: 14, fill: "rgba(20,18,16,0.45)" },
      // a small potted plant in the lower-right foreground that occludes the
      // sofa edge when the camera dollies right.
      { kind: "rect", x: 1140, y: 612, w: 70, h: 60, fill: "#a87038" },
      {
        kind: "rect",
        x: 1140,
        y: 612,
        w: 70,
        h: 60,
        fill: { gradient: "linear", x0: 1140, y0: 612, x1: 1210, y1: 672, stops: [{ at: 0, color: "rgba(255,235,200,0.3)" }, { at: 1, color: "rgba(0,0,0,0.3)" }] },
      },
      { kind: "ellipse", cx: 1175, cy: 612, rx: 60, ry: 36, fill: "#3a6f47" },
      { kind: "ellipse", cx: 1158, cy: 596, rx: 28, ry: 22, fill: "#4a874e" },
      { kind: "ellipse", cx: 1198, cy: 600, rx: 26, ry: 20, fill: "#386542" },
    ],
  },
};

// Doorway scene — used to validate sceneChange + parallax with a different
// foreground silhouette. Background is hallway/outdoor light; midground is the
// open door + threshold; foreground is the doorframe edge.
const doorwayShape: ProceduralShape = {
  preview: { fit: "contain" },
  parallax: { background: 0.28, midground: 1, foreground: 1.5 },
  primitives: [],
  layers: {
    background: [
      // hallway wall gradient
      {
        kind: "rect",
        x: -200,
        y: 0,
        w: 1680,
        h: 720,
        fill: {
          gradient: "linear",
          x0: 0,
          y0: 0,
          x1: 0,
          y1: 720,
          stops: [
            { at: 0, color: "#e3d9c6" },
            { at: 0.55, color: "#c4b497" },
            { at: 0.56, color: "#7e5f48" },
            { at: 1, color: "#4d3a2d" },
          ],
        },
      },
      // outdoor sky behind the open door — sunset glow
      {
        kind: "rect",
        x: 500,
        y: 140,
        w: 280,
        h: 480,
        fill: {
          gradient: "linear",
          x0: 0,
          y0: 140,
          x1: 0,
          y1: 620,
          stops: [
            { at: 0, color: "#f6c98a" },
            { at: 0.55, color: "#c97d63" },
            { at: 1, color: "#5b3e3a" },
          ],
        },
      },
      // sun glow disc
      {
        kind: "circle",
        cx: 640,
        cy: 320,
        r: 110,
        fill: {
          gradient: "radial",
          x0: 640,
          y0: 320,
          r0: 0,
          x1: 640,
          y1: 320,
          r1: 110,
          stops: [
            { at: 0, color: "rgba(255, 240, 200, 0.85)" },
            { at: 1, color: "rgba(255, 240, 200, 0)" },
          ],
        },
      },
    ],
    midground: [
      // floor strip
      { kind: "rect", x: -200, y: 545, w: 1680, h: 175, fill: "#6e4a35" },
      {
        kind: "rect",
        x: -200,
        y: 545,
        w: 1680,
        h: 175,
        fill: { gradient: "linear", x0: 0, y0: 545, x1: 0, y1: 720, stops: [{ at: 0, color: "rgba(255,235,200,0.18)" }, { at: 1, color: "rgba(0,0,0,0.3)" }] },
      },
      // open door panel (recessed in the frame)
      { kind: "roundedRect", x: 740, y: 140, w: 180, h: 480, r: 8, fill: "#7a4f36", shadow: { blur: 18, offsetX: -6, color: "rgba(0,0,0,0.32)" } },
      {
        kind: "roundedRect",
        x: 740,
        y: 140,
        w: 180,
        h: 480,
        r: 8,
        fill: { gradient: "linear", x0: 740, y0: 140, x1: 920, y1: 620, stops: [{ at: 0, color: "rgba(255,255,255,0.18)" }, { at: 1, color: "rgba(0,0,0,0.32)" }] },
      },
      // doorknob
      { kind: "circle", cx: 760, cy: 400, r: 7, fill: "#d9b46b" },
      // a coat rack on the left wall
      { kind: "rect", x: 120, y: 220, w: 12, h: 280, fill: "#6e4a35" },
      { kind: "circle", cx: 126, cy: 215, r: 12, fill: "#a47a4a" },
      { kind: "roundedRect", x: 75, y: 240, w: 110, h: 70, r: 20, fill: "#3e5e6f" },
    ],
    foreground: [
      // doorframe left + right (left frame in front of door, right frame is
      // the wall edge)
      { kind: "rect", x: 480, y: 80, w: 30, h: 560, fill: "#3e2a1f" },
      { kind: "rect", x: 950, y: 80, w: 30, h: 560, fill: "#3e2a1f" },
      { kind: "rect", x: 480, y: 80, w: 500, h: 60, fill: "#3e2a1f" },
      // floor-edge shadow strip
      {
        kind: "rect",
        x: -100,
        y: 690,
        w: 1480,
        h: 30,
        fill: { gradient: "linear", x0: 0, y0: 690, x1: 0, y1: 720, stops: [{ at: 0, color: "rgba(20,14,10,0.4)" }, { at: 1, color: "rgba(20,14,10,0)" }] },
      },
    ],
  },
};

export const sampleLibrary: AssetLibrary = {
  globalAssets: [
    {
      assetId: "character_father_template",
      name: "父亲模板",
      category: "visual",
      type: "character",
      scope: "global",
      source: { kind: "manual", format: "procedural", originalFile: "built-in" },
      files: { preview: "procedural://father" },
      tags: ["adult", "family", "template"],
      metadata: {
        width: 260,
        height: 520,
        anchor: { x: 130, y: 500 },
        palette: { body: "#2c3e50", skin: "#f0b985", hair: "#33271f", pants: "#3b2f24" },
        parts: ["body", "face", "hair", "expression", "costume", "voice"],
        displayName: "父亲",
        actions: HUMAN_CHARACTER_ACTIONS,
        expressions: HUMAN_CHARACTER_EXPRESSIONS,
        shape: humanCharacterShape,
      },
      license: {
        type: "internal-demo",
        author: "Cucumber Engine",
        sourceUrl: "",
        commercialUse: true,
        needAttribution: false,
      },
    },
    {
      assetId: "effect_flash_001",
      name: "情绪闪光",
      category: "visual",
      type: "effect",
      scope: "global",
      source: { kind: "manual", format: "procedural", originalFile: "built-in" },
      files: { preview: "procedural://flash" },
      tags: ["emotion", "flash"],
      metadata: { blendMode: "screen", defaultDuration: 0.8, shape: flashEffectShape },
      license: {
        type: "internal-demo",
        author: "Cucumber Engine",
        sourceUrl: "",
        commercialUse: true,
        needAttribution: false,
      },
    },
  ],
  projectAssets: [
    {
      assetId: "scene_living_room_001",
      name: "客厅场景",
      category: "visual",
      type: "scene",
      scope: "project",
      source: { kind: "manual", format: "scene-json", originalFile: "living-room.scene.json" },
      files: { config: "living-room.scene.json", preview: "procedural://living-room" },
      tags: ["living-room", "family"],
      metadata: { width: 1280, height: 720, layers: ["background", "midground", "foreground"], shape: livingRoomShape },
      license: {
        type: "internal-demo",
        author: "Cucumber Engine",
        sourceUrl: "",
        commercialUse: true,
        needAttribution: false,
      },
    },
    {
      assetId: "scene_doorway_001",
      name: "门口场景",
      category: "visual",
      type: "scene",
      scope: "project",
      source: { kind: "manual", format: "scene-json", originalFile: "doorway.scene.json" },
      files: { config: "doorway.scene.json", preview: "procedural://doorway" },
      tags: ["doorway", "family"],
      metadata: { width: 1280, height: 720, layers: ["background", "midground", "foreground"], shape: doorwayShape },
      license: {
        type: "internal-demo",
        author: "Cucumber Engine",
        sourceUrl: "",
        commercialUse: true,
        needAttribution: false,
      },
    },
    {
      assetId: "character_father_001",
      name: "父亲",
      category: "visual",
      type: "character",
      scope: "project",
      source: { kind: "referenced", format: "procedural", originalFile: "character_father_template" },
      files: { preview: "procedural://father" },
      tags: ["father", "family"],
      metadata: {
        width: 260,
        height: 520,
        anchor: { x: 130, y: 500 },
        palette: { body: "#2c3e50", skin: "#f0b985", hair: "#33271f", pants: "#3b2f24" },
        expressions: HUMAN_CHARACTER_EXPRESSIONS,
        actions: HUMAN_CHARACTER_ACTIONS,
        shape: humanCharacterShape,
      },
      license: {
        type: "internal-demo",
        author: "Cucumber Engine",
        sourceUrl: "",
        commercialUse: true,
        needAttribution: false,
      },
      overrides: { role: "father", costume: "blue jacket" },
    },
    {
      assetId: "character_child_001",
      name: "孩子",
      category: "visual",
      type: "character",
      scope: "project",
      source: { kind: "manual", format: "procedural", originalFile: "built-in" },
      files: { preview: "procedural://child" },
      tags: ["child", "family"],
      metadata: {
        width: 210,
        height: 430,
        anchor: { x: 105, y: 410 },
        palette: { body: "#c64b3a", skin: "#f3c092", hair: "#403026", pants: "#2a3f5a" },
        expressions: HUMAN_CHARACTER_EXPRESSIONS,
        actions: HUMAN_CHARACTER_ACTIONS,
        shape: childCharacterShape,
      },
      license: {
        type: "internal-demo",
        author: "Cucumber Engine",
        sourceUrl: "",
        commercialUse: true,
        needAttribution: false,
      },
    },
    {
      assetId: "character_warrior_001",
      name: "格斗家",
      category: "visual",
      type: "character",
      scope: "project",
      source: { kind: "manual", format: "procedural", originalFile: "built-in" },
      files: { preview: "procedural://warrior" },
      tags: ["warrior", "fighter", "spiky"],
      metadata: {
        width: 260,
        height: 520,
        anchor: { x: 130, y: 500 },
        // KOF-style: black jacket, orange pants, fiery red spiky hair, tanned skin.
        palette: { body: "#1f1814", skin: "#f0bf95", hair: "#d33a17", pants: "#ef6d2c" },
        displayName: "格斗家",
        expressions: HUMAN_CHARACTER_EXPRESSIONS,
        actions: HUMAN_CHARACTER_ACTIONS,
        shape: warriorCharacterShape,
      },
      license: {
        type: "internal-demo",
        author: "Cucumber Engine",
        sourceUrl: "",
        commercialUse: true,
        needAttribution: false,
      },
    },
    {
      assetId: "character_explorer_001",
      name: "海岛少年",
      category: "visual",
      type: "character",
      scope: "project",
      source: { kind: "manual", format: "procedural", originalFile: "built-by-script" },
      files: { preview: "procedural://explorer" },
      tags: ["adventure", "explorer", "straw-hat"],
      metadata: {
        width: 260,
        height: 520,
        anchor: { x: 130, y: 500 },
        // Original explorer palette: green vest, brown shorts, dark hair under a straw hat.
        palette: { body: "#3a6e4a", skin: "#f0bf95", hair: "#2a1e16", pants: "#7a5230" },
        displayName: "少年",
        expressions: HUMAN_CHARACTER_EXPRESSIONS,
        actions: HUMAN_CHARACTER_ACTIONS,
        shape: explorerCharacterShape,
        references: [
          { sourceType: "open-format", source: "scripts/build-character-shape.ts", note: "Generated via the character shape builder script — demonstrates straw hat + open vest + shorts + scar mark." },
        ],
      },
      license: {
        type: "internal-demo",
        author: "Cucumber Engine",
        sourceUrl: "",
        commercialUse: true,
        needAttribution: false,
      },
    },
    {
      assetId: "prop_schoolbag_001",
      name: "书包",
      category: "visual",
      type: "prop",
      scope: "project",
      source: { kind: "manual", format: "procedural", originalFile: "built-in" },
      files: { preview: "procedural://schoolbag" },
      tags: ["prop", "school"],
      metadata: { width: 130, height: 110, anchor: { x: 65, y: 100 }, shape: schoolbagShape },
      license: {
        type: "internal-demo",
        author: "Cucumber Engine",
        sourceUrl: "",
        commercialUse: true,
        needAttribution: false,
      },
    },
  ],
  scenes: [
    {
      sceneId: "scene_living_room_001",
      name: "客厅",
      background: "scene_living_room_001",
      foreground: "scene_living_room_001",
      points: {
        door: { x: 160, y: 520 },
        sofa: { x: 790, y: 535 },
        center: { x: 610, y: 535 },
        table: { x: 620, y: 585 },
      },
      objects: [
        { id: "sofa_001", type: "obstacle", movable: false, x: 820, y: 565 },
        { id: "prop_schoolbag_001", type: "prop", movable: true, assetId: "prop_schoolbag_001", x: 430, y: 615 },
      ],
      cameraPoints: {
        wide: { x: 640, y: 360, zoom: 1 },
        door: { x: 320, y: 390, zoom: 1.35 },
        sofaClose: { x: 790, y: 390, zoom: 1.55 },
      },
    },
    {
      sceneId: "scene_doorway_001",
      name: "门口",
      background: "scene_doorway_001",
      foreground: "scene_doorway_001",
      points: {
        threshold: { x: 730, y: 600 },
        coatRack: { x: 130, y: 480 },
      },
      objects: [],
      cameraPoints: {
        wide: { x: 640, y: 360, zoom: 1 },
        door: { x: 740, y: 380, zoom: 1.3 },
      },
    },
  ],
};

export const sampleProject: Project = {
  projectId: "project_family_argument_001",
  title: "父子争吵",
  description: "一个 25 秒家庭情感短剧片段，用于验证黄瓜引擎 2.5D 短剧底座的资产、章节、片段、时间线、镜头和 Web 预览闭环。",
  assetRefs: [
    "scene_living_room_001",
    "scene_doorway_001",
    "character_father_001",
    "character_child_001",
    "character_warrior_001",
    "character_explorer_001",
    "prop_schoolbag_001",
    "effect_flash_001",
  ],
  config: { resolution: "1280x720", fps: 30 },
  preview: { activeChapterId: "chapter_001", activeSegmentId: "segment_001" },
  export: { includeAssets: true, includeTimeline: true },
  aiReserved: {
    assetGenerationEndpoint: "",
    timelineGenerationEndpoint: "",
    acceptedSchemas: ["asset-manifest.v1", "project.v1", "timeline-event.v1"],
  },
  chapters: [
    {
      chapterId: "chapter_001",
      title: "争吵开始",
      sceneId: "scene_living_room_001",
      characters: ["character_father_001", "character_child_001"],
      transition: { type: "fadeIn", duration: 1 },
      bgm: undefined,
      segments: [
        {
          segmentId: "segment_001",
          name: "孩子进门",
          duration: 25,
          timeline: [
            { time: 0, type: "sceneChange", sceneId: "scene_doorway_001" },
            // Open at the door but offset LEFT — gives us camera headroom
            // to pan right and show parallax immediately.
            {
              time: 0,
              type: "cameraChange",
              camera: { mode: "wide", x: 460, y: 360, zoom: 1, duration: 0, transition: "cut" },
            },
            // Father is deep inside the room (z = 240) — reads ~60% smaller
            // and noticeably dimmer than a foreground character.
            {
              time: 0.8,
              type: "characterAppear",
              target: "character_father_001",
              position: { x: 830, y: 545, z: 240 },
              expression: "neutral",
              scale: 1,
            },
            // Child stands at the threshold, basically AT the camera (z = 0).
            {
              time: 1.2,
              type: "characterAppear",
              target: "character_child_001",
              position: { x: 720, y: 600, z: 0 },
              expression: "neutral",
              scale: 0.95,
            },
            { time: 1.5, type: "subtitle", text: "孩子推门进来，客厅里的空气一下安静了。", duration: 3 },
            // Big initial pan RIGHT — large cameraDX so background drifts
            // slowly and the floor lamp / doorframe rip through fast. This
            // is the "parallax is real" beat the user will see in the first
            // few seconds.
            {
              time: 1.8,
              type: "cameraChange",
              camera: { mode: "medium", x: 880, y: 380, zoom: 1.18, duration: 2.0, transition: "smooth" },
            },
            // SceneChange to the living room as the child crosses the
            // threshold — visually a sceneChange, narratively a continuation.
            { time: 4, type: "sceneChange", sceneId: "scene_living_room_001" },
            // Open the living room shot also offset LEFT so the next pan
            // right re-triggers parallax instead of starting at rest.
            {
              time: 4,
              type: "cameraChange",
              camera: { mode: "wide", x: 460, y: 360, zoom: 1, duration: 0.8, transition: "smooth" },
            },
            { time: 4.2, type: "characterAction", target: "character_child_001", action: { name: "walking", params: {} } },
            // Child walks deeper INTO the room — z rises from 0 → 80 so
            // they shrink AND dim as they walk away from camera.
            { time: 4.2, type: "characterMove", target: "character_child_001", to: { x: 480, y: 545, z: 80 }, duration: 4 },
            { time: 8.2, type: "characterAction", target: "character_child_001", action: { name: "idle", params: {} } },
            // Slow continuous pan across the room while the child walks —
            // this is what makes the floor lamp + sofa parallax read.
            {
              time: 4.5,
              type: "cameraChange",
              camera: { mode: "wide", x: 820, y: 360, zoom: 1, duration: 4, transition: "smooth" },
            },
            {
              time: 8.5,
              type: "cameraChange",
              camera: { mode: "medium", x: 565, y: 405, zoom: 1.25, duration: 1.4, transition: "smooth" },
            },
            { time: 9.6, type: "expressionChange", target: "character_father_001", expression: "angry" },
            // Father throws an angry "attack" pose during the harsh line — the
            // new shape supports it; right arm thrusts forward.
            { time: 9.6, type: "characterAction", target: "character_father_001", action: { name: "attack", params: {} } },
            { time: 9.8, type: "dialogue", target: "character_father_001", text: "这么晚才回来？", duration: 2.2 },
            { time: 11.6, type: "characterAction", target: "character_father_001", action: { name: "idle", params: {} } },
            {
              time: 10.0,
              type: "effectPlay",
              effectId: "effect_flash_001",
              position: { x: 820, y: 250 },
              duration: 0.8,
            },
            { time: 12.0, type: "expressionChange", target: "character_child_001", expression: "sad" },
            // Child shrinks into a "defend" pose — arms crossed at chest.
            { time: 12.0, type: "characterAction", target: "character_child_001", action: { name: "defend", params: {} } },
            { time: 12.2, type: "dialogue", target: "character_child_001", text: "我只是想把作业做完。", duration: 2.8 },
            { time: 15.0, type: "characterAction", target: "character_child_001", action: { name: "idle", params: {} } },
            // Close-up on the child also yanks them back to z = 0 — clear
            // contrast against the still-distant father.
            {
              time: 15.0,
              type: "cameraChange",
              camera: { mode: "closeUp", target: "character_child_001", zoom: 1.65, duration: 1.2, transition: "smooth" },
            },
            { time: 15.0, type: "characterMove", target: "character_child_001", to: { x: 480, y: 545, z: 0 }, duration: 0.2 },
            { time: 16, type: "subtitle", text: "镜头推近，孩子低头攥紧了书包带。", duration: 3 },
            { time: 17.5, type: "characterAction", target: "character_child_001", action: { name: "walking", params: {} } },
            // Child walks toward father — z climbs from 0 → 200 so they
            // visibly shrink as they cross the room.
            { time: 17.5, type: "characterMove", target: "character_child_001", to: { x: 600, y: 545, z: 200 }, duration: 2.5 },
            { time: 20, type: "characterAction", target: "character_child_001", action: { name: "idle", params: {} } },
            {
              time: 20.2,
              type: "cameraChange",
              camera: { mode: "wide", x: 640, y: 360, zoom: 1, duration: 1.6, transition: "smooth" },
            },
            { time: 21.5, type: "expressionChange", target: "character_father_001", expression: "soft" },
            { time: 22.0, type: "dialogue", target: "character_father_001", text: "先坐下，我们慢慢说。", duration: 2.7 },
          ],
        },
      ],
    },
  ],
};
